### ISSUE TITLE
Crosslinking restraint outputs take -log of score

### ISSUE THREAD

**Issue by sethaxen** [salilab/pmi#236] opened 2017-08-01 19:04 UTC
Several of the cross-linking restraints add -log of score to outputs. Not only does this seem weird, but since the score can be negative, in some cases this will raise an error. Examples are [here](https://github.com/salilab/pmi/blob/7807950f0843d0d68b95b0b3971c722f2402c8b3/pyext/src/restraints/crosslinking.py#L408) and [here](https://github.com/salilab/pmi/blob/7807950f0843d0d68b95b0b3971c722f2402c8b3/pyext/src/restraints/crosslinking.py#L2115).

Is this simply an oversight or was this done for a reason?

**Comment by Pellarin** [comment] 2017-08-03 00:51
The reason is the following: the CrossLinkMSRestartaint returns the probability and not the score, which is always less than one. All restrants are wrapped in the LogWrapperRestraint to finally return the total score.

**Comment by benmwebb** [comment] 2021-08-06 07:29
Closing, not a bug.

**Closed as completed by benmwebb** 2021-08-06 07:29 UTC
Labels: bug
