### ISSUE TITLE
Alternative/enhanced functionality for sequence

### ISSUE THREAD

**Issue by Pellarin** [salilab/pmi#122] opened 2015-06-23 22:44 UTC
```
        seqs = IMP.pmi.topology.Sequences('seqs.fasta')
        seqs.create_sequences('Protein_1','Prot1')
        seqs.create_sequences('Protein_2','Prot2')
        seqs.create_sequences('Protein_3','Prot3')
```

**Comment by benmwebb** [comment] 2021-08-06 05:56
Not sure what was intended here; closing for now.

**Closed as completed by benmwebb** 2021-08-06 05:56 UTC
