### ISSUE TITLE
psf writing in Output segfaults with gaussians in hierarchy

### ISSUE THREAD

**Issue by saltzberg** [salilab/pmi#173] opened 2016-02-18 23:08 UTC
Test added in 3279018388f1d9e6270815f37bdd0baea03f4b5b.  Sorry, it's a segFault test.  

I've added Gaussians to the PMI2 hierarchy using `gemt.add_target_density_to_hierarchy(st1.get_hierarchy())` and now when writing PSF files, I get a segfault that I've narrowed down to inside `Output.get_particles_for_pdb_writing()`.

**Comment by saltzberg** [comment] 2016-02-18 23:17
Narrowed down further to when the Gaussian particle is passed to `IMP.pmi.get_molecule_name_and_copy()`

**Comment by cgreenberg** [comment] 2016-02-18 23:28
A few problems with your test:
- you haven't called `setup_particles_as_densities=True` for the non-atomic regions, so those won't be Gaussians. 
- why are you testing PSF writing? Do you mean PDB writing? To be honest I haven't yet even checked if PSF writing is working with regular PMI2 hierarchies (I'm not really sure if anyone uses that). Would RMF writing be sufficient? That should work fine. 
- The PDB writing, at least, is expecting a canonical structure. That means every leaf particle is part of a `Fragment` or `Atom`, and leaf is a child of a `Fragment` that is also a `Representation`, etc. You've just added a random hierarchy that isn't even made of Atom or Fragment particles so it doesn't know what to do with them. Probably we should make the PDB/PSF writing code skip these nodes (maybe checking to see if it's made of fragments or not). 
- A bigger problem is your code `add_target_density_to_hierarchy` - which level is the user supposed to add this to? You added it to the state, but nothing is stopping a user from adding it somewhere else. You'll either have to make sure the PDB writing is OK if it encounters these nodes at ANY level, or change `add_target_density_to_hierarchy` to only add it to a specific place.

**Comment by cgreenberg** [comment] 2016-02-18 23:32
Ah, I see you do set them us as `Fragments`. The problem is there is no `Molecule`. Probably the easiest solution is, in `gem::get_density_as_hierarchy`, to pretend the EM map is a new molecule. Set it up as a `Molecule` and `Chain`, then add the `Fragment` as a child, then add the EM particles as children to the `Fragment` (as you do now). If you want to write them to PDB, you'll have to make them `Resolution=X` nodes. But I'm not sure you want them in the PDB/PSF file.

You can then edit your code to ensure the EM "Molecule" is always added as the child of the State node.

**Comment by saltzberg** [comment] 2016-02-18 23:33
> why are you testing PSF writing? Do you mean PDB writing? To be honest I haven't yet even checked if PSF writing is working with regular PMI2 hierarchies (I'm not really sure if anyone uses that). Would RMF writing be sufficient? That should work fine.

Both PDB and PSF writing fail, but the initial segfault came while PSF writing, line 316 in `macros.py`.  Took me a while to narrow down the cause.

> The PDB writing, at least, is expecting a canonical structure. That means every leaf particle is part of a Fragment or Atom, and leaf is a child of a Fragment that is also a Representation, etc. You've just added a random hierarchy that isn't even made of Atom or Fragment particles so it doesn't know what to do with them. Probably we should make the PDB/PSF writing code skip these nodes (maybe checking to see if it's made of fragments or not).

Agreed.  I'm not looking to write these to PDB.  I'd just like to figure out how to skip them so we don't crash (and throw an exception rather than crash!)

**Comment by cgreenberg** [comment] 2016-02-18 23:37
Yeah, IMP.pmi.get_molecule_name_and_copy() is failing because the particles aren't a part of a molecule. I think everything will work fine if you create the EM nodes as children of a node decorated as Molecule (name="EM map" ?) and Copy (=0).

**Comment by cgreenberg** [comment] 2016-02-19 17:52
OK making progress!  A few notes on the current test:
- You're getting the "duplicate node" problem because of an apparent bug. For your system, the `IMP.atom.DENSITIES` type is not used - that's only used for _atomic_ structures currently. So that `Selection` should return an empty list. For some reason it's returning...the root node. I'll look into it, but you only have to pass the non atomic residues (or in this case all the residues) to the restraint.
- Looks like you don't have to bother making things a `Chain` or a `Representation`. I'd just use this code for `get_density_as_hierarchy`:

``` python
    def get_density_as_hierarchy(self):
        if self.em_root_hier is None:
            self.em_root_hier = IMP.atom.Copy.setup_particle(IMP.Particle(self.m),0)
            self.em_root_hier.set_name("GaussianEMRestraint_density_"+self.label)
            for p in self.target_ps:
                self.em_root_hier.add_child(p)
        return self.em_root_her
```

And then for `add_target_density_to_hierarchy` just call `st_hier.add_child(self.get_density_as_hierarchy())`
- Note that it's better to avoid working with `locals()`. Instead just set `self.em_root_hier=None` in the restraint's `__init__` constructor
- Now that the nodes are in the hierarchy, you can do a few cool things. Like `IMP.atom.show_with_representations(root_hier)` should display the EM map particles. And because you gave the EM 'molecule' a name you can actually use `Selection` to get those particles back:

``` python
        sel1 = IMP.atom.Selection(hier,molecule='GaussianEMRestraint_density_em_1')
        print sel1.get_selected_particles()
```

Just make sure you call System.build() instead of Molecule.build() so that `hier` is the system root hierarchy.

**Comment by cgreenberg** [comment] 2016-02-19 18:55
OK fixed in salilab/imp@0256df96ac22cb54cd6bd760af1e60477b0be54c so selection with `representation_type=IMP.atom.DENSITIES` should return an empty list if none were created.

**Comment by saltzberg** [comment] 2016-02-19 22:21
fixed with d1f13d0a1e01841e522c7bdde5f6e9f2866215eb.  Thanks, Charles.

**Comment by cgreenberg** [comment] 2016-02-23 19:48
So there's still a slight issue, Riccardo was using the function `add_target_density_to_hierarchy`, plus it needs to work with PMI1 (sadly). That's why tests are failing. So maybe change it back from the State requirement and use the old function name. Just add some documentation that the user SHOULD pass a state hierarchy.

Also you could combine the tests `test_GaussianEMRestraint_rigidbody.py` and `test_add_gaussians_to_hierarchy.py`

**Comment by cgreenberg** [comment] 2016-02-23 19:49
Note that you'll need the changes I just committed to `atom` for things to work. Sorry.

**Comment by cgreenberg** [comment] 2016-02-26 00:49
@saltzberg Thoughts?

**Closed as completed** 2016-03-05 22:02 UTC
